# Generated by Django 3.1 on 2020-12-10 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорий',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='user/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ выполнен')], default='new', max_length=100, verbose_name='Статус заказ')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='Тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения заказа')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='main.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('title_description', models.CharField(max_length=100, verbose_name='Описание на обложке')),
                ('gameplay_description', models.TextField(verbose_name='Геймплей')),
                ('story_description', models.TextField(verbose_name='Сюжет')),
                ('game_features_description', models.TextField(verbose_name='Игровые особенности')),
                ('language_text', models.CharField(max_length=25, verbose_name='Язык текста')),
                ('language_voise', models.CharField(max_length=25, verbose_name='Язык озвучки')),
                ('os', models.CharField(max_length=50, verbose_name='Операцеонная система')),
                ('cpu', models.CharField(max_length=50, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=50, verbose_name='Оперативка')),
                ('gpu', models.CharField(max_length=50, verbose_name='Видеокарта')),
                ('hard_disk', models.CharField(max_length=50, verbose_name='Жёсткий диск')),
                ('data', models.IntegerField(default=0, verbose_name='Дата выхода')),
                ('image_1', models.ImageField(upload_to='game/', verbose_name='1) Изображение из игры')),
                ('image_2', models.ImageField(upload_to='game/', verbose_name='2) Изображение из игры')),
                ('image_3', models.ImageField(upload_to='game/', verbose_name='3) Изображение из игры')),
                ('image_4', models.ImageField(upload_to='game/', verbose_name='4) Изображение из игры')),
                ('image_wrapper', models.ImageField(upload_to='game/', verbose_name='Обложка')),
                ('torrent', models.FileField(upload_to='torrents/', verbose_name='Torrent файл')),
                ('like', models.IntegerField(default='0', verbose_name='Нравиться')),
                ('dislike', models.IntegerField(default='0', verbose_name='Не нравиться')),
                ('views', models.IntegerField(default='0', verbose_name='Просмотры')),
                ('pro', models.CharField(max_length=1, verbose_name='PRO')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоймость игры')),
                ('category', models.ManyToManyField(to='main.Category', verbose_name='Категорий')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='buys',
            field=models.ManyToManyField(blank=True, related_name='related_buys', to='main.Game'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=25, verbose_name='Имя автора')),
                ('comment_text', models.CharField(max_length=100, verbose_name='Коментарий')),
                ('comment_time', models.DateTimeField(auto_now=True, verbose_name='дата коментария')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии к играм',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='main.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Продукт корзины',
                'verbose_name_plural': 'Продукт корзины',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='main.CartProduct'),
        ),
    ]
