# Generated by Django 3.2 on 2021-04-18 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': '4) Корзина',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорий',
                'verbose_name_plural': '2) Категорий',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='design/icon/', verbose_name='Иконка сайта')),
                ('background', models.ImageField(upload_to='design/theme/', verbose_name='Фон сайта')),
                ('logotype', models.ImageField(upload_to='design/logotype/', verbose_name='Логотип сайта')),
            ],
            options={
                'verbose_name': 'Фон сайта',
                'verbose_name_plural': '7) Дизайн сайта',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('title_description', models.TextField(max_length=180, verbose_name='Описание на обложке')),
                ('gameplay_description', models.TextField(verbose_name='Геймплей')),
                ('story_description', models.TextField(verbose_name='Сюжет')),
                ('game_features_description', models.TextField(verbose_name='Игровые особенности')),
                ('language_text', models.CharField(max_length=25, verbose_name='Язык текста')),
                ('language_voise', models.CharField(max_length=25, verbose_name='Язык озвучки')),
                ('os', models.CharField(max_length=50, verbose_name='Операцеонная система')),
                ('cpu', models.CharField(max_length=50, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=50, verbose_name='Оперативка')),
                ('gpu', models.CharField(max_length=50, verbose_name='Видеокарта')),
                ('hard_disk', models.CharField(max_length=50, verbose_name='Жёсткий диск')),
                ('data', models.IntegerField(default=0, verbose_name='Дата выхода игры')),
                ('image_1', models.ImageField(upload_to='game/2021-04-18', verbose_name='1) Изображение из игры')),
                ('image_2', models.ImageField(upload_to='game/2021-04-18', verbose_name='2) Изображение из игры')),
                ('image_3', models.ImageField(upload_to='game/2021-04-18', verbose_name='3) Изображение из игры')),
                ('image_4', models.ImageField(upload_to='game/2021-04-18', verbose_name='4) Изображение из игры')),
                ('image_wrapper', models.ImageField(upload_to='game/', verbose_name='Обложка')),
                ('torrent', models.FileField(upload_to='torrent/', verbose_name='Torrent файл')),
                ('like', models.IntegerField(default='0', verbose_name='Нравиться')),
                ('dislike', models.IntegerField(default='0', verbose_name='Не нравиться')),
                ('views', models.IntegerField(default='0', verbose_name='Просмотры')),
                ('pro', models.CharField(max_length=1, verbose_name='PRO')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоймость игры')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикаций игры на сайте')),
                ('category', models.ManyToManyField(to='main.Category', verbose_name='Категорий')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': '1) Игры',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=80, null=True, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='user/avatar/', verbose_name='Аватарка')),
                ('list_of_purchased_games', models.ManyToManyField(blank=True, related_name='related_list_of_purchased_games', to='main.Game', verbose_name='Список приобретённых игр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': '6) Пользователи (Дополнительно)',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=25, verbose_name='Имя автора')),
                ('author_image', models.ImageField(blank=True, upload_to='user/avatar/', verbose_name='Аватарка')),
                ('account_level', models.IntegerField(default='0', verbose_name='Уровень аккаунта')),
                ('comment_text', models.CharField(max_length=100, verbose_name='Коментарий')),
                ('comment_time', models.DateTimeField(auto_now=True, verbose_name='дата коментария')),
                ('comment_rank_up', models.IntegerField(default='0', verbose_name='Нравиться')),
                ('comment_rank_down', models.IntegerField(default='0', verbose_name='Не нравиться')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': '3) Коментарии',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='main.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Продукт в корзине',
                'verbose_name_plural': '5) Продукты в корзине',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='main.CartProduct'),
        ),
    ]
