# Generated by Django 3.2 on 2021-04-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='background',
            field=models.ImageField(null=True, upload_to='design/theme/', verbose_name='Фон сайта'),
        ),
        migrations.AlterField(
            model_name='design',
            name='icon',
            field=models.ImageField(null=True, upload_to='design/icon/', verbose_name='Иконка сайта'),
        ),
        migrations.AlterField(
            model_name='design',
            name='logotype',
            field=models.ImageField(null=True, upload_to='design/logotype/', verbose_name='Логотип сайта'),
        ),
    ]
