# Generated by Django 3.1 on 2020-12-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='buys',
            new_name='list_of_purchased_games',
        ),
    ]
