# Generated by Django 3.2 on 2021-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210418_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='background',
            field=models.ImageField(default='g', null=True, upload_to='design/theme/', verbose_name='Фон сайта'),
        ),
        migrations.AlterField(
            model_name='design',
            name='icon',
            field=models.ImageField(default='g', null=True, upload_to='design/icon/', verbose_name='Иконка сайта'),
        ),
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='design',
            name='logotype',
            field=models.ImageField(default='g', null=True, upload_to='design/logotype/', verbose_name='Логотип сайта'),
        ),
    ]
