# Generated by Django 3.1 on 2020-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201210_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='list_of_purchased_games',
            field=models.ManyToManyField(blank=True, related_name='related_list_of_purchased_games', to='main.Game', verbose_name='Список купленных игр'),
        ),
    ]
