# Generated by Django 3.1 on 2020-12-11 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20201210_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': '4) Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': '5) Продукты в корзине'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорий', 'verbose_name_plural': '2) Категорий'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': '3) Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '6) Пользователи (Дополнительно)'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': '1) Игры'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=80, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='list_of_purchased_games',
            field=models.ManyToManyField(blank=True, related_name='related_list_of_purchased_games', to='main.Game', verbose_name='Список приобретённых игр'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title_description',
            field=models.TextField(max_length=100, verbose_name='Описание на обложке'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
