# Generated by Django 3.1 on 2020-12-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201211_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title_description',
            field=models.TextField(max_length=140, verbose_name='Описание на обложке'),
        ),
    ]
