# Generated by Django 3.1 on 2020-12-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201211_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title_description',
            field=models.TextField(max_length=180, verbose_name='Описание на обложке'),
        ),
    ]
