# Generated by Django 3.1 on 2020-12-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201211_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='comment',
            name='account_level',
            field=models.IntegerField(default='0', verbose_name='Уровень аккаунта'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='user/', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_rank_down',
            field=models.IntegerField(default='0', verbose_name='Не нравиться'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_rank_up',
            field=models.IntegerField(default='0', verbose_name='Нравиться'),
        ),
    ]
